.\"                                      Hey, EMACS: -*- nroff -*-
.\" $Id: ruli.3,v 1.2 2004/03/26 18:09:10 evertonm Exp $
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH RULI 3 "March 26, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ruli \- Library for querying DNS SRV resource records (RFC 2782)
.SH SYNOPSIS
.B ruli
.SH DESCRIPTION
This manual page documents briefly the
.B ruli
library.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBruli\fP is a library aimed at querying DNS SRV resource records.
.SH SEE ALSO
The library is documented fully by
.IR "The RULI Tutorial" ,
available at http://www.nongnu.org/ruli/.
.br
RFC 2782 - A DNS RR for specifying the location of services (DNS SRV)
.SH AUTHOR
This manual page was written by Everton da Silva Marques <evertonsm@yahoo.com.br>.
